import type { CollectionConfig } from 'payload'

export const ProductVariants: CollectionConfig = {
  slug: 'product-variants',
  admin: {
    useAsTitle: 'name',
    defaultColumns: ['name', 'uid', 'product', 'isCommercial'],
  },
  access: {
    read: () => true,
    create: ({ req: { user } }) => user?.collection === 'admin-users',
    update: ({ req: { user } }) => user?.collection === 'admin-users',
    delete: ({ req: { user } }) => user?.collection === 'admin-users',
  },
  fields: [
    {
      type: 'row',
      fields: [
        {
          name: 'name',
          type: 'text',
          required: true,
          admin: {
            width: '50%',
          },
        },
        {
          name: 'uid',
          type: 'text',
          required: true,
          unique: true,
          admin: {
            description: 'Unique identifier (e.g. "essentials", "pro", "trial")',
            width: '50%',
          },
        },
      ],
    },
    {
      type: 'row',
      fields: [
        {
          name: 'description',
          type: 'text',
          required: true,
          admin: {
            width: '50%',
          },
        },
        {
          name: 'product',
          type: 'relationship',
          relationTo: 'products',
          required: true,
          admin: {
            width: '50%',
          },
        },
      ],
    },
    {
      name: 'hierarchy',
      type: 'number',
      min: 1,
      admin: {
        description:
          'Variant hierarchy level in app (e.g. Elements=1, Player=2, Loops=3, Beats=4, Composer=5).',
        width: '50%',
      },
    },
    {
      name: 'lemonSqueezyVariantId',
      type: 'text',
      admin: {
        description: 'The numeric Variant ID generated by Lemon Squeezy (e.g., 472910)',
        width: '50%',
      },
    },
    {
      name: 'priceCents',
      type: 'number',
      admin: {
        description: 'Base direct purchase price in cents. Used for discount code validation.',
      },
    },
    {
      name: 'isCommercial',
      type: 'checkbox',
      admin: {
        description:
          'Marks this variant as commercial (paid). Leave unchecked for free/community variants.',
      },
    },
  ],
  timestamps: true,
}
