/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    'admin-users': AdminUserAuthOperations;
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    'admin-users': AdminUser;
    users: User;
    media: Media;
    pages: Page;
    orders: Order;
    'contact-submissions': ContactSubmission;
    products: Product;
    'product-variants': ProductVariant;
    licenses: License;
    installations: Installation;
    'welcome-licenses': WelcomeLicense;
    affiliates: Affiliate;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    'admin-users': AdminUsersSelect<false> | AdminUsersSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    'contact-submissions': ContactSubmissionsSelect<false> | ContactSubmissionsSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    'product-variants': ProductVariantsSelect<false> | ProductVariantsSelect<true>;
    licenses: LicensesSelect<false> | LicensesSelect<true>;
    installations: InstallationsSelect<false> | InstallationsSelect<true>;
    'welcome-licenses': WelcomeLicensesSelect<false> | WelcomeLicensesSelect<true>;
    affiliates: AffiliatesSelect<false> | AffiliatesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    homepage: Homepage;
    manual: Manual;
    downloads: Download;
    'register-welcome-email': RegisterWelcomeEmail;
    'purchase-welcome-email': PurchaseWelcomeEmail;
  };
  globalsSelect: {
    homepage: HomepageSelect<false> | HomepageSelect<true>;
    manual: ManualSelect<false> | ManualSelect<true>;
    downloads: DownloadsSelect<false> | DownloadsSelect<true>;
    'register-welcome-email': RegisterWelcomeEmailSelect<false> | RegisterWelcomeEmailSelect<true>;
    'purchase-welcome-email': PurchaseWelcomeEmailSelect<false> | PurchaseWelcomeEmailSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: AdminUser | User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface AdminUserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admin-users".
 */
export interface AdminUser {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'admin-users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Optional notes about this user
   */
  info?: string | null;
  /**
   * Prevent this user from logging in
   */
  blocked?: boolean | null;
  /**
   * User opted in to receive marketing emails
   */
  marketingConsent?: boolean | null;
  /**
   * The affiliate partner who referred this user
   */
  referredBy?: (number | null) | Affiliate;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  _verified?: boolean | null;
  _verificationToken?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "affiliates".
 */
export interface Affiliate {
  id: number;
  /**
   * Friendly name or company name for this partner
   */
  name: string;
  /**
   * Tracking code used in URLs or embedded in Player keys (e.g. "john20")
   */
  affiliateCode: string;
  /**
   * Toggle to temporarily disable tracking and payouts
   */
  active: boolean;
  /**
   * Link to the actual user account registered in our system
   */
  user: number | User;
  /**
   * Rules applied when a user registers or buys via an affiliate tracking link
   */
  linkStrategy: {
    enabled?: boolean | null;
    isLifetime?: boolean | null;
    /**
     * Commission for the user's very first transaction
     */
    firstPurchaseRate: number;
    /**
     * Commission for following purchases (only if Lifetime is enabled)
     */
    subsequentPurchaseRate?: number | null;
  };
  /**
   * Rules applied when a user binds their account using a physical license key from this partner
   */
  keyStrategy: {
    enabled?: boolean | null;
    isLifetime?: boolean | null;
    commissionRate: number;
  };
  /**
   * Internal admin notes, logs, or reasons for deactivation
   */
  info?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * URL slug (e.g. terms-and-conditions)
   */
  slug: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  user: number | User;
  source: 'lemon_squeezy' | 'plugin_boutique';
  /**
   * The order identifier from the external system (e.g., Order Number)
   */
  externalOrderId: string;
  /**
   * Transaction amount in cents/lowest currency unit (integer)
   */
  amount: number;
  affiliatePartner?: (number | null) | Affiliate;
  /**
   * Commission percentage granted for this specific order (e.g., 10 or 20)
   */
  affiliateRate?: number | null;
  affiliatePayoutStatus?: ('none' | 'pending' | 'paid') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions".
 */
export interface ContactSubmission {
  id: number;
  email: string;
  subject: string;
  message: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  name: string;
  /**
   * Unique identifier for the product (e.g. "mx-grid")
   */
  uid: string;
  version: string;
  /**
   * Numeric version used for license version range checks
   */
  versionNo: number;
  releasedAt: string;
  releaseUpdatedAt: string;
  description?: string | null;
  thumb?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-variants".
 */
export interface ProductVariant {
  id: number;
  name: string;
  /**
   * Unique identifier (e.g. "essentials", "pro", "trial")
   */
  uid: string;
  description: string;
  product: number | Product;
  /**
   * The numeric Variant ID generated by Lemon Squeezy (e.g., 472910)
   */
  lemonSqueezyVariantId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "licenses".
 */
export interface License {
  id: number;
  product: number | Product;
  user: number | User;
  userEmail?: string | null;
  productVariants?: (number | ProductVariant)[] | null;
  /**
   * Leave empty for unlimited validity
   */
  validTill?: string | null;
  active?: boolean | null;
  deactivatedReason?: string | null;
  versionFrom: number;
  versionTo: number;
  info?: string | null;
  maxInstallations?: number | null;
  /**
   * Associated purchase order transaction
   */
  order?: (number | null) | Order;
  /**
   * Affiliate partner who distributed this specific key (e.g., for Player variant)
   */
  preassignedPartner?: (number | null) | Affiliate;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "installations".
 */
export interface Installation {
  id: number;
  user: number | User;
  product: number | Product;
  machineId: string;
  computerName?: string | null;
  os?: string | null;
  token: string;
  /**
   * Base64-encoded XML certificate
   */
  certificate: string;
  disabled?: boolean | null;
  disabledAt?: string | null;
  disabledReason?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Licenses that are automatically assigned to new users upon registration
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "welcome-licenses".
 */
export interface WelcomeLicense {
  id: number;
  product: number | Product;
  productVariants?: (number | ProductVariant)[] | null;
  versionFrom: number;
  versionTo: number;
  info?: string | null;
  maxInstallations: number;
  /**
   * Number of days the license is valid. Leave empty for unlimited.
   */
  daysValid?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'admin-users';
        value: number | AdminUser;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'contact-submissions';
        value: number | ContactSubmission;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'product-variants';
        value: number | ProductVariant;
      } | null)
    | ({
        relationTo: 'licenses';
        value: number | License;
      } | null)
    | ({
        relationTo: 'installations';
        value: number | Installation;
      } | null)
    | ({
        relationTo: 'welcome-licenses';
        value: number | WelcomeLicense;
      } | null)
    | ({
        relationTo: 'affiliates';
        value: number | Affiliate;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'admin-users';
        value: number | AdminUser;
      }
    | {
        relationTo: 'users';
        value: number | User;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'admin-users';
        value: number | AdminUser;
      }
    | {
        relationTo: 'users';
        value: number | User;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admin-users_select".
 */
export interface AdminUsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  info?: T;
  blocked?: T;
  marketingConsent?: T;
  referredBy?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  _verified?: T;
  _verificationToken?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  content?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  user?: T;
  source?: T;
  externalOrderId?: T;
  amount?: T;
  affiliatePartner?: T;
  affiliateRate?: T;
  affiliatePayoutStatus?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions_select".
 */
export interface ContactSubmissionsSelect<T extends boolean = true> {
  email?: T;
  subject?: T;
  message?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  uid?: T;
  version?: T;
  versionNo?: T;
  releasedAt?: T;
  releaseUpdatedAt?: T;
  description?: T;
  thumb?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-variants_select".
 */
export interface ProductVariantsSelect<T extends boolean = true> {
  name?: T;
  uid?: T;
  description?: T;
  product?: T;
  lemonSqueezyVariantId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "licenses_select".
 */
export interface LicensesSelect<T extends boolean = true> {
  product?: T;
  user?: T;
  userEmail?: T;
  productVariants?: T;
  validTill?: T;
  active?: T;
  deactivatedReason?: T;
  versionFrom?: T;
  versionTo?: T;
  info?: T;
  maxInstallations?: T;
  order?: T;
  preassignedPartner?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "installations_select".
 */
export interface InstallationsSelect<T extends boolean = true> {
  user?: T;
  product?: T;
  machineId?: T;
  computerName?: T;
  os?: T;
  token?: T;
  certificate?: T;
  disabled?: T;
  disabledAt?: T;
  disabledReason?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "welcome-licenses_select".
 */
export interface WelcomeLicensesSelect<T extends boolean = true> {
  product?: T;
  productVariants?: T;
  versionFrom?: T;
  versionTo?: T;
  info?: T;
  maxInstallations?: T;
  daysValid?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "affiliates_select".
 */
export interface AffiliatesSelect<T extends boolean = true> {
  name?: T;
  affiliateCode?: T;
  active?: T;
  user?: T;
  linkStrategy?:
    | T
    | {
        enabled?: T;
        isLifetime?: T;
        firstPurchaseRate?: T;
        subsequentPurchaseRate?: T;
      };
  keyStrategy?:
    | T
    | {
        enabled?: T;
        isLifetime?: T;
        commissionRate?: T;
      };
  info?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  hero?: {
    heroImage?: (number | null) | Media;
    headline1?: string | null;
    headline2?: string | null;
    subline?: string | null;
  };
  intro?: {
    text?: string | null;
    ctaLabel?: string | null;
    ctaUrl?: string | null;
  };
  features?:
    | {
        heading: string;
        description: string;
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  timeline?: {
    heading?: string | null;
    subheading?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  pricing?:
    | {
        feature: string;
        essentials: string;
        loops: string;
        beats?: string | null;
        composer?: string | null;
        id?: string | null;
      }[]
    | null;
  demo: {
    demoHeading: string;
    demoDescription: string;
    demoUrl: string;
    demoBtnLabel: string;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "manual".
 */
export interface Manual {
  id: number;
  /**
   * Sidebar navigation HTML
   */
  aside: string;
  /**
   * Mobile table of contents HTML
   */
  mobileToc: string;
  /**
   * Manual sections rendered in order
   */
  sections: {
    /**
     * Section HTML content
     */
    html: string;
    id?: string | null;
  }[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "downloads".
 */
export interface Download {
  id: number;
  intro: {
    /**
     * Introductory paragraph shown above the download list
     */
    text: string;
    /**
     * Note shown at the bottom of the page (e.g. registration requirement)
     */
    note: string;
  };
  /**
   * Download groups (e.g. Windows, macOS)
   */
  downloads: {
    /**
     * Group heading (e.g. "Installer for MS Windows 64 bit")
     */
    title: string;
    /**
     * Individual files available for this group
     */
    files: {
      description: string;
      /**
       * Version number (e.g. 1.2.0)
       */
      version?: string | null;
      fileName: string;
      size: string;
      url: string;
      id?: string | null;
    }[];
    id?: string | null;
  }[];
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Email template sent to new users after email verification, along with welcome licenses
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "register-welcome-email".
 */
export interface RegisterWelcomeEmail {
  id: number;
  subject: string;
  /**
   * Plain text version of the email
   */
  text: string;
  /**
   * HTML version of the email
   */
  html: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Email template sent after a successful purchase. Supported template variables: {{applicationName}}, {{variantName}}, {{loginEmail}}, {{loginPassword}}, {{externalOrderId}}, {{downloadsUrl}}, {{userPanelUrl}}, {{signInUrl}}, {{accountSecurityNotice}}
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "purchase-welcome-email".
 */
export interface PurchaseWelcomeEmail {
  id: number;
  /**
   * Available variables: {{applicationName}}, {{variantName}}, {{loginEmail}}, {{loginPassword}}, {{externalOrderId}}, {{downloadsUrl}}, {{userPanelUrl}}, {{signInUrl}}, {{accountSecurityNotice}}
   */
  subject: string;
  /**
   * Plain text version. Available variables: {{applicationName}}, {{variantName}}, {{loginEmail}}, {{loginPassword}}, {{externalOrderId}}, {{downloadsUrl}}, {{userPanelUrl}}, {{signInUrl}}, {{accountSecurityNotice}}
   */
  text: string;
  /**
   * HTML version. Available variables: {{applicationName}}, {{variantName}}, {{loginEmail}}, {{loginPassword}}, {{externalOrderId}}, {{downloadsUrl}}, {{userPanelUrl}}, {{signInUrl}}, {{accountSecurityNotice}}
   */
  html: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        heroImage?: T;
        headline1?: T;
        headline2?: T;
        subline?: T;
      };
  intro?:
    | T
    | {
        text?: T;
        ctaLabel?: T;
        ctaUrl?: T;
      };
  features?:
    | T
    | {
        heading?: T;
        description?: T;
        image?: T;
        id?: T;
      };
  timeline?:
    | T
    | {
        heading?: T;
        subheading?: T;
        description?: T;
        image?: T;
      };
  pricing?:
    | T
    | {
        feature?: T;
        essentials?: T;
        loops?: T;
        beats?: T;
        composer?: T;
        id?: T;
      };
  demo?:
    | T
    | {
        demoHeading?: T;
        demoDescription?: T;
        demoUrl?: T;
        demoBtnLabel?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "manual_select".
 */
export interface ManualSelect<T extends boolean = true> {
  aside?: T;
  mobileToc?: T;
  sections?:
    | T
    | {
        html?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "downloads_select".
 */
export interface DownloadsSelect<T extends boolean = true> {
  intro?:
    | T
    | {
        text?: T;
        note?: T;
      };
  downloads?:
    | T
    | {
        title?: T;
        files?:
          | T
          | {
              description?: T;
              version?: T;
              fileName?: T;
              size?: T;
              url?: T;
              id?: T;
            };
        id?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "register-welcome-email_select".
 */
export interface RegisterWelcomeEmailSelect<T extends boolean = true> {
  subject?: T;
  text?: T;
  html?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "purchase-welcome-email_select".
 */
export interface PurchaseWelcomeEmailSelect<T extends boolean = true> {
  subject?: T;
  text?: T;
  html?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}